hash-format = "sha256"

[[files]]
file = "config/item_obliterator.json5"
hash = "246809f67d66ec62d3cff6d28cb885d26b2cd2cc16cceb64a4da4dc763c4da2d"

[[files]]
file = "config/paxi/datapack_load_order.json"
hash = "89a86742f6110ea11b461860ec4eda79e3adf059272f1e1a0f2e1e6690dfd736"

[[files]]
file = "config/paxi/datapacks/Alex's Mobs Compat 1.0.zip"
hash = "e8b21a29a591bb5d8975840a56e41d8d3db925b61e7885ed5c1d4180502f7b2c"

[[files]]
file = "config/paxi/datapacks/BOP_MES_compat_datapack 1.20-1.21.zip"
hash = "0ade36f208e2e91e33806979e3e0832e5eead6cc827e14c6658800fa5b120451"

[[files]]
file = "config/paxi/datapacks/BoP x FD Bark Cutting Compat.zip"
hash = "40aca9f794a08cec9c352967602bf7033246156e07d613f849ff1e6d75f42c32"

[[files]]
file = "config/paxi/datapacks/Farmer's Delight Cutting Compat 1.0.zip"
hash = "e7444cde0a4df808545b1b89daab457516ff6d879ee969a98957c00c5f1923a3"

[[files]]
file = "config/paxi/datapacks/NoMoreFloatingIslands-1.20.1-1.0.0.zip"
hash = "59bcb031c1ca0b4c2403983f0bf62b7d846a1b8b1d426ec548135a1963441cff"

[[files]]
file = "config/paxi/datapacks/Quark x FD Bark Cutting Compat.zip"
hash = "427b8043a2f75efc9fc4306ded555e8bef2a8c62fea80247adf14f510efe71d4"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Better_Dungeons_v5.zip"
hash = "a6d7837bf6ddacfa7521f44dd1ee14bdbb7c0b6152857e175791fc7fa537d915"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Better_Strongholds_v5.zip"
hash = "4ecace941dbbef488669ff6a6e44088b2bdc9e83662855b24d28d49a171152dd"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Better_Witch_Huts_v4.zip"
hash = "009bbea81fb0f500ebea78112cbecee7bf2f94bf3301a342442f850132e47476"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Bountiful_v3.zip"
hash = "880d7a0791d51be8e93fafb8e1181f2f6b6eb655642f36786803291a5c2770cf"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Bygone_Nether_v1.zip"
hash = "673aa581e76dc4582edfa954d2502c42c5c44074967f666382ebc4d80185ba85"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Bygone_Nether_v2.zip"
hash = "645938a5c414791163bae88a8a464183ec8642c64a172a01993ee675553656e4"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Farmers_Delight_v6.zip"
hash = "ff899242a00ddafb7fdb7d7a2b0654f1da06f3ac1a85bbb0a0512489dcf51272"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Friends_And_Foes_v5.zip"
hash = "8a2cfd70366a5671012e6c70c97ff1f9058f24ce56d4a1e466904fd06f141fbe"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Illager_Invasion_v2.zip"
hash = "5d23e33b962c4978e53b550feb10f8b0aeee6c6dcb0aceb20ff5d69783ac59d4"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-Sawmill_v2.zip"
hash = "335c5251bc6cd00e06bd6f4a82aab3051a7cac2e21d0a4bc1988ef6e170d335b"

[[files]]
file = "config/paxi/datapacks/Repurposed_Structures-VillagersPlus_v3.zip"
hash = "592e56cf4c9f4bba6f7c7585003c9b223d73737e9ab3c7d8c5a0273a8a489b8d"

[[files]]
file = "config/paxi/datapacks/Scaring_The_Scarecrows_1.20.1.zip"
hash = "d7fb8cf0993be5d5e5477e69e43de5acdbda567c4388e3eb3ab9fac5052d1039"

[[files]]
file = "config/paxi/datapacks/Supplementaries Compat 1.0.zip"
hash = "c8ae1fe5df63bc985415ce09017948f65714f5befaa1f4c6d2f9a888f21ef432"

[[files]]
file = "config/paxi/datapacks/comforts_ropenail_fix.zip"
hash = "e62bee06da90968cfe8d4c3e61d0f96aa21f3ee2d8e975d7028f80efaf49ded3"

[[files]]
file = "config/paxi/datapacks/end_city_spacing.zip"
hash = "c53a7f3822c51914d3fc64cc81294077cd03ef98503303aa3e6cd8ca24911ab1"

[[files]]
file = "config/paxi/datapacks/formationsoverworldconfig.zip"
hash = "56e19786aed6858fcb58ba370ffc3390901edbb9e11a92285e38956a1d6509fa"

[[files]]
file = "config/paxi/datapacks/ichphilipp-s-endcity-better-end-1-18-1.zip"
hash = "29f133eb00798f3440719f5fdec9ca46de0311fb97e480cb19bdbc3f610f8048"

[[files]]
file = "config/paxi/resourcepack_load_order.json"
hash = "89a86742f6110ea11b461860ec4eda79e3adf059272f1e1a0f2e1e6690dfd736"

[[files]]
file = "config/resourcepackoverrides.json"
hash = "4df494aed1e605f6ed5bc3c1a21905410cec7d85b7cc8dc7820f76f32942dc1c"

[[files]]
file = "config/subtle_effects/items.toml"
hash = "bd00d8134e13054e066075099c10f6124b87fab0309f57c8957ed9c1726d7b9c"

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "6a144cc70e30220d743320fd99debd3aeab1dc6c4913cafa9cf8f02a020c5344"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "255367152563bbfab3cf37af0902539e39426b0fcd0358538a69b12576e9a2b8"
metafile = true

[[files]]
file = "mods/create-blocks-bogies.pw.toml"
hash = "48593789853beef0f3a4fe3184b61c0df48f8f0f10cc3b7436ebab7e335b8c7f"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "f3210935646f7b029ad3e3b0f7b917cb72305ac43b51a8cb9849a7b38e7c20e2"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "cc98c01686dca35eb74faf1a39fe006f0517ee2095f64922fdbd7d26c64a7f50"
metafile = true

[[files]]
file = "mods/create-escalated.pw.toml"
hash = "24b4b865f408c6a24f75c5327de85ea11726b78231d1cd8271ebfef77174f1c8"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "5a900258b61fce618695f42c4a4d07d1190984135e07dc67996544904b2ef9d0"
metafile = true

[[files]]
file = "mods/create-let-the-adventure-begin.pw.toml"
hash = "6096a07dd33855cd468dd11d5ac7e740a303087ada197dde2593619c0b29c14d"
metafile = true

[[files]]
file = "mods/create-liquid-fuel.pw.toml"
hash = "6a7621e5afac1d388c1645261460e7318eff195cf4419d8902153b22a5f24294"
metafile = true

[[files]]
file = "mods/create-misc-and-things.pw.toml"
hash = "be63e960eb88c7f7972219245d939f2cb90c2b2eb882b67217c9d185f1f1305f"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "053339e6cd1d20ad23dc80504fb3cee0d428043614aedd4f7f0f7fa790f7b11f"
metafile = true

[[files]]
file = "mods/create-o-plenty.pw.toml"
hash = "1126b2fe3619ca51331df471a84cc654a2b2c3b66faf7650b98f319489ff67b7"
metafile = true

[[files]]
file = "mods/create-picky-waterwheels.pw.toml"
hash = "5e8c4cc0e33299a669f78aef285cad75903302a8014e2f538b798e237d908792"
metafile = true

[[files]]
file = "mods/create-radars.pw.toml"
hash = "bf6ac91d8f5b8d53c60b6e85272d533cd61f0d58c410f54ca66e8d9e06446f58"
metafile = true

[[files]]
file = "mods/create-railways-navigator.pw.toml"
hash = "b4daf3e8501adf885496a09cc262ec0fbd7a26a8593f530c7ef2d24a316fe558"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "f12b1658ed6fa8009a428e32053131d392d78d4290f216e8bd0c28bb38d2838a"
metafile = true

[[files]]
file = "mods/create-tweaked-controllers.pw.toml"
hash = "89db426dfb5f947a8b449b8c58460947cadda7c73f5ad1f2eec20b2ba1c33432"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "e408c93a8ce2b0cc8ecb1b9b8ae6dc5e51075f27a6ad06958551ee3a6edc750b"
metafile = true

[[files]]
file = "mods/dragonlib.pw.toml"
hash = "94e1ae26546c1150e0b0eb4b9254d34e850a93a78a5c56319538db72f076f897"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "361a2451dc12db42636eed5aab8c03f8a281347504e0131346a3ec8b8273333b"
metafile = true

[[files]]
file = "mods/hypertubes.pw.toml"
hash = "29ecd5f4d3a19bf6e39d480dc71edc13c8a8acd3631e79614491be4e4c6bb1b0"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "409d1c425dec85a17a31365b2b0e20b2a05e2b1c32639a22871e693f4dc604de"
metafile = true

[[files]]
file = "mods/ritchies-projectile-library.pw.toml"
hash = "ead47b2f294c0e5434df9d0389d2474d8f3536656976c7e73d1e3f8a4e7c26ae"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "6650168c5eacebe05e9fad8eb19a8e5ef937ecc6e88b909a1231d49896e66b61"
metafile = true

[[files]]
file = "resourcepacks/Better_Modded_GUI.zip"
hash = "e161a18333fb2bf8acb897cf689f7f1419d9dba1fe341a98316395953df3ffb4"

[[files]]
file = "resourcepacks/Mandalas_Legacy_Gui_Background.zip"
hash = "b243fcadf46d00d033a1b8e99025b1c023796879dfea34cd5a2e586fee1f5b4f"

[[files]]
file = "resourcepacks/NoBushyLeaves.zip"
hash = "b3751ee1742c1cef6f283af8be45d50d51a4359534f0f469cc9dcfb6b69c17e1"

[[files]]
file = "resourcepacks/Quark Programmer Art.zip"
hash = "41cb720cf256a12ea247b2f38068b363aa5b1675470c4b5aa66850701a78bc4d"

[[files]]
file = "resourcepacks/SE Vanilla Consistency 1.20.1.zip"
hash = "767ad33f82139a8be0c246262d8a70074cddc2e09f74fb39e9c9dd3d509eb46f"

[[files]]
file = "resourcepacks/animated-door.pw.toml"
hash = "031a54437d0ac582056ff190637d37530b33f0e7e3f0478b4391b2df8d7b0fb2"
metafile = true

[[files]]
file = "resourcepacks/armor-trim-compats.pw.toml"
hash = "33cb4b385fbbd9419c634d08c9c6356026a8d0038796e866263810c6e0e0f182"
metafile = true

[[files]]
file = "resourcepacks/backpacked-recipe-fix.pw.toml"
hash = "7c1fda29d2b72e5ef1d207260a2bff1d52cee633311e842d770dae337b78cc1b"
metafile = true

[[files]]
file = "resourcepacks/beautiful-enchanted-books.pw.toml"
hash = "14904dc53ab9bf2b97dfba40dd4a3ac0b071eca81e752edd02549d83ffa15e9f"
metafile = true

[[files]]
file = "resourcepacks/better-end-city-for-better-end.pw.toml"
hash = "1a7217e81d1857c0b04018f2751399230ec5cf37a9a0d0dc4baaf0ac281dee7c"
metafile = true

[[files]]
file = "resourcepacks/biomes-o-plenty-x-farmers-delight-bark-cutting.pw.toml"
hash = "eb72af4ac07b79d7ab03449379fd7e2d247aadbf8c622faa3b9abc8f210d4527"
metafile = true

[[files]]
file = "resourcepacks/created-simple-storage-network.pw.toml"
hash = "b66026bea52d1890fc4bf818d37527a917fcff5d1903aeef8b19930fcc38491e"
metafile = true

[[files]]
file = "resourcepacks/enchantment-descriptions-compat.pw.toml"
hash = "4854e86b7e50c0b707c7001e9c4565acfa8a642ebf83e3a05ce87b6c840d3199"
metafile = true

[[files]]
file = "resourcepacks/farmers-delight-cutting-compat.pw.toml"
hash = "8931bb9797e1764e737cd4db05d926feef1681946a051b5ca788e6a4294cfac9"
metafile = true

[[files]]
file = "resourcepacks/fresh-waystones-texture.pw.toml"
hash = "926e90d0c821bed39efbbc29bd7f1df3547ed8fe44e7272f758ee1aa3d8246fd"
metafile = true

[[files]]
file = "resourcepacks/mandala-gui-dark-mode-utopia-extension.pw.toml"
hash = "1fb712b3f3cd5d260f4f1e648297d5b8dbe2458698f05eb9770df8ea6a650f4d"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "8ed45d3cf487c5ed8736050223b1b4211d79b44587031238afae1844199727cc"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-vanilla-crosshair.pw.toml"
hash = "eb741014bc2b31d8e92c601ba1211ca17924df1252f61a041c54b7c397672ad5"
metafile = true

[[files]]
file = "resourcepacks/modded-omelet.pw.toml"
hash = "012d8c20612a02900c4e619f34198478cc6b091ad9aa8cee5dbeebbb48dce020"
metafile = true

[[files]]
file = "resourcepacks/quark-x-farmers-delight-bark-cutting-compat.pw.toml"
hash = "54901630fd3fe5b45885d94741a5f1d0458e4dc1dfe177dfcc8c21287b9eb338"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-better-dungeons-datapack.pw.toml"
hash = "4606bc35642254b48c9a05c922d27d3907d3773152a2b7829699ea785234dc3c"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-better-strongholds-datapack.pw.toml"
hash = "34642fe7342ea4eb6576735bd8e709a2e720f9025e3a0716b9b29d78f50278fd"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-better-witch-huts-compat.pw.toml"
hash = "f35f43b64e4a1e07971945172eea9f6b301d7a6d33b26b9436bddbf3f8928f51"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-bountiful-datapack-compat.pw.toml"
hash = "b827b6140e7049515098f2c6d9d94d6a79dc5eff996eb7c64892f0cfe578fb05"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-bygone-nether-compat.pw.toml"
hash = "d223c7de1c77fefd76b79f71914cbc66eecb29cfc59a2d53499b34b62f9dcaab"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-farmers-delight-datapack.pw.toml"
hash = "ef870e505548d3ee232eb07c3e027f7806b82c00e0adc9c6a2e5fe69fd8f0550"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-friends-and-foes-datapack.pw.toml"
hash = "77a920c4c061924e0a792e982450414fcd4d292ca073fd44c9c2b715b3747f69"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-sawmill-compat.pw.toml"
hash = "9a900a562b8b03d3fa7b15125d9928c262a7434fe6b21c859e2d34f8cd410744"
metafile = true

[[files]]
file = "resourcepacks/repurposed-structures-villagerplus-compat-datapack.pw.toml"
hash = "467ddc17285358cd70ad8814dd3e21410c2fb4acc8efc941a992193531fc25fe"
metafile = true

[[files]]
file = "resourcepacks/scaring-the-scarecrows.pw.toml"
hash = "c1c074d44d5c6998230c48d589d38df95e882aca0c4c9eea8e39f5374a8cbd9f"
metafile = true

[[files]]
file = "resourcepacks/stay-true.pw.toml"
hash = "d3fdcf524452ad021f4089230a56ff0e4a9472eb0a5555048c905008e2eb6db3"
metafile = true

[[files]]
file = "resourcepacks/sweetys-items-alexs-mobs.pw.toml"
hash = "955b809feb159d6d63716e6d92480b6a090950807e59276fa6fae359592b5cb7"
metafile = true

[[files]]
file = "resourcepacks/the-rename-compat-project.pw.toml"
hash = "59762cbb7156c5aa21855cc125bb4ad639059c14705d7c8ccdf0263d2f5398cb"
metafile = true
