name = "Better MC 4 Forge (Memphis)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4382642316dfa63b42e86ef12bd0c3bd208c623466850b9e4403827f2f63162d"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
