name = "Better MC 4 Forge (Memphis)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51659a4501c7d1f3700199bf9dc5ac8815a6ea698d4a11b90f652e3a99b685ec"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
